### ISSUE TITLE
Its not working

### ISSUE THREAD

**Issue by krahamath** [mnlg/evento#1]
Its not working to add event.

**Comment by mnlg** [comment]
Some files and folders were missing, it should work now.

**Comment by krahamath** [comment]
Thanks, i have updated files and it now showing `Warning: include(Cake\bootstrap.php): failed to open stream: No such file or directory in C:\wamp\www\evento\webroot\index.php on line 100` and `Fatal error: CakePHP core could not be found. Check the value of CAKE_CORE_INCLUDE_PATH in APP/webroot/index.php. It should point to the directory containing your \cake core directory and your \vendors root directory. in C:\wamp\www\evento\webroot\index.php on line 109`

**Comment by mnlg** [comment]
Make sure you're using CakePHP 2.9, download it from https://github.com/cakephp/cakephp/releases as it's not included in this repository.

**Comment by krahamath** [comment]
Sorry, i can't understand.This not included with all cakephp files?

**Comment by mnlg** [comment]
Download CakePHP 2.9 and replace the app/ folder with evento.

**Comment by krahamath** [comment]
Downloaded 2.9.3 and replaced app folder from evento(your new updated files). Installation comes and next registration gives error (`
An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.
`)
but user saved in tables and login works. But when i started to add event or venue nothing shown even error but form validation are working.
